/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://papermc.io/repo/repository/maven-public/")
    }
}

rootProject.name = "TeamArenaPaper"
