name: TeamArenaPaper
version: '${project.version}'
main: me.toomuchzelda.teamarenapaper.Main
api-version: 1.18
authors: [ toomuchzelda ]
depend: [ProtocolLib]
description: Minigames inspired by libraryaddict's Search and Destroy
